/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.wgh.actionForm;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 11-27-2007
 * 
 * XDoclet definition:
 * @struts.form name="parameterForm"
 */
public class ParameterForm extends ActionForm {

	private int ID;
	//private String sn;
	private String device;
	private String baud;
	public int getID() {
		return ID;
	}
	public void setID(int iD) {
		ID = iD;
	}
	/*public String getSn() {
		return sn;
	}
	public void setSn(String sn) {
		this.sn = sn;
	}*/
	public String getDevice() {
		return device;
	}
	public void setDevice(String device) {
		this.device = device;
	}
	public String getBaud() {
		return baud;
	}
	public void setBaud(String baud) {
		this.baud = baud;
	}
	
}